management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Datenbank-Verbindung für PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/buergermeldebox
spring.datasource.username=buergermeldebox
spring.datasource.password=buergermeldebox
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true